export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCESS = "AUTH_LOGIN_SUCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ACTION = "SIGN_UP_ACTION";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const UPDATE_SIGN_IN_RESPONSE = "UPDATE_SIGN_UP_RESPONSE";
export const UPDATE_USERS_LIST = "UPDATE_USERS_LIST";
export const UPDATE_CONVERSATIONS_LIST = "UPDATE_CONVERSATIONS_LIST";
export const POST_MESSAGE_DATA = "POST_MESSAGE_DATA";
export const ADD_MESSAGE_TO_CONVERSATIONS = "ADD_MESSAGE_TO_CONVERSATIONS";
export const REFRESH_CHAT = "REFRESH_CHAT";
export const LOGOUT = "LOGOUT";
